MVCDay2/Controllers/CourseNewController.cs
using Microsoft.AspNetCore.Mvc;
using MVCDay2.Models;
using Microsoft.EntityFrameworkCore;
using System.Reflection;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using System.Text;
using Humanizer;
using System.Numerics;

namespace MVCDay2.Controllers
{
    public class CourseNewController : Controller
    {
        MyContext context = new MyContext();
        public IActionResult Show()
        {
            List<Course> listCourse = context.Courses.ToList();
            return View(listCourse);
        }   

        [HttpGet]
        public IActionResult New() 
        {
            ViewBag.DeptList = context.Departments.ToList();
            ViewBag.ResultsList = context.CRSresults.ToList();
            ViewBag.InstList = context.Instractors.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult New(Course course)
        {
            try
            {
                //if (course.CourseName != null)
                if (ModelState.IsValid == true)//Validation server side
                {
                    context.Add(course);
                    context.SaveChanges();
                    return RedirectToAction("Show");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "check any error ");
            }
            ViewBag.ResultsList = context.CRSresults.ToList();
            ViewBag.DeptList = context.Departments.ToList();
            ViewBag.InstList = context.Instractors.ToList();

            return View (course);
        }

        [HttpGet]
        public IActionResult Delete(int id) 
        {
            Course course = context.Courses.Find(id);

            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, string confirmButton)
        {
            Course course = context.Courses.Find(id);

            //if (course == null)
            //{
            //    return NotFound();
            //}

            context.Courses.Remove(course);
            context.SaveChanges();

            return RedirectToAction("Show");
           
        }

        public IActionResult CheckMinDegree(int CourseDegree,int CourseMinDegree)
        {
            if (CourseMinDegree >= CourseDegree)
            {
                return Json(false);
            }

            return Json(true);

        }
      

    }

}

MVCDay2/Views/CourseNew/Delete.cshtml
@model Course

@* @{
    Layout = "~/Views/Shared/_AdvanLayout.cshtml";
} *@

    <title>Delete Confirmation:@Html.DisplayFor(Model => Model.CourseName)</title>


 
    <h2>Delete Confirmation</h2>

    <div>
        <p>
            Please confirm you want to delete course titled:
            <i>@Html.DisplayFor(Model => Model.CourseName)</i>
           
        </p>
    </div>

    <form asp-action="Delete" asp-controller="CourseNew" asp-route-id="@Model.Id" method="post">
        <input name="confirmButton" type="submit" value="Delete" />

       
        <a asp-controller="CourseNew" asp-action="Show" class="btn btn-secondary">Cancel</a>
    </form>

MVCDay2/Views/CourseNew/New.cshtml
@model Course
@{
    ViewData["Title"] = "New";
    SelectList DeptItems = new SelectList(ViewBag.DeptList, "Id", "DeptName");
    SelectList InstItems = new SelectList(ViewBag.InstList, "Id", "InsName");
    SelectList ResultsItems = new SelectList(ViewBag.ResultsList, "Id","ICrsDegree");
}

<h1>New</h1>

<form method="post" asp-action="New" asp-controller="CourseNew">
    <div asp-validation-summary="All" class="text-danger"></div>
   
    <div>
   
    <div>
        <label asp-for="CourseName"></label>
        <input asp-for="CourseName" class="form form-control" />
        <span asp-validation-for="CourseName" class="text-danger"></span>
    </div>
        <div>
            <label asp-for="CourseDegree"></label>
            <input asp-for="CourseDegree" class="form form-control" />
            <span asp-validation-for="CourseDegree" class="text-danger"></span>
        </div>
    <div>
        <label asp-for="CourseMinDegree"></label>
        <input asp-for="CourseMinDegree" class="form form-control" />
        <span asp-validation-for="CourseMinDegree" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="DeptId"></label>

        <select asp-for="DeptId" asp-items="DeptItems" class="form form-control">
                <option value="0"> --Select Department-- </option>

        </select>
        <span asp-validation-for="DeptId" class="text-danger"></span>
    </div>
    <br/>
    <input type="submit" value="Create" class="btn btn-success" />
    <a href="/CourseNew/Show" class="btn btn-dark">Back to Cources</a>
</form>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

MVCDay2/Views/CourseNew/Show.cshtml
@using MVCDay2.Models
@model List<Course>
@{
    ViewData["Title"] = "Show";
   // Layout = "~/Views/Shared/_AdvanLayout.cshtml";

}

<h1>Show</h1>

<table class="table table-bordered table-hover">
    <tr>
        <th>Id</th>
        <th>Course Name</th>
        <th>Course Degree</th>
        <th>Min Degree</th>
        <th>New Course</th>
        <th>Delete Course</th>
    </tr>
    @foreach (var item in Model )
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.CourseName</td>
            <td>@item.CourseDegree</td>
            <td>@item.CourseMinDegree</td>
            <td>
                <a asp-action="New" asp-controller="CourseNew" class="btn btn-success">New</a>

             </td>
            <td>
                <a href="/CourseNew/Delete/@item.Id" class="btn btn-danger">Delete</a></td>
        </tr>
    }
</table>